### ISSUE TITLE
Samples roadmap

### ISSUE THREAD

**Issue by xaviervia** [jstp/node-jstp#11]
**regular**
- [x] regular/local { get post put delete patch }
- [x] regular/tcp/single-step { host get post put delete patch }
- [x] regular/tcp/two-steps { host proxy get post put delete patch }
- [x] regular/ws/single-step { host get post put delete patch }
- [x] regular/ws/two-steps { host proxy get post put delete patch }

**subscription**
- [x] subscription/local/bind/methods { get post put patch delete wildcard }
- [x] subscription/local/bind/resource { literal named asterisk ellipsis }
- [x] subscription/local/release/methods { get post put patch delete wildcard }
- [x] subscription/local/release/resource { literal named asterisk ellipsis }
- [x] subscription/tcp/single-step/bind/method { get post put patch delete wildcard }
- [x] subscription/tcp/single-step/bind/resource { literal named asterisk ellipsis }
- [x] subscription/tcp/single-step/release/method { get post put patch delete wildcard }
- [x] subscription/tcp/single-step/release/resource { literal named asterisk ellipsis }
- [x] subscription/tcp/two-steps/bind/method { get post put patch delete wildcard }
- [x] subscription/tcp/two-steps/bind/resource { literal named asterisk ellipsis }
- [x] subscription/tcp/two-steps/release/method { get post put patch delete wildcard }
- [x] subscription/tcp/two-steps/release/resource { literal named asterisk ellipsis }
- [x] subscription/ws/single-step/bind/method { get post put patch delete wildcard }
- [x] subscription/ws/single-step/bind/resource { literal named asterisk ellipsis }
- [x] subscription/ws/single-step/release/method { get post put patch delete wildcard }
- [x] subscription/ws/single-step/release/resource { literal named asterisk ellipsis }
- [x] subscription/ws/two-steps/bind/method { get post put patch delete wildcard }
- [x] subscription/ws/two-steps/bind/resource { literal named asterisk ellipsis }
- [x] subscription/ws/two-steps/release/method { get post put patch delete wildcard }
- [x] subscription/ws/two-steps/release/resource { literal named asterisk ellipsis }

**answer**
- [ ] answer/local/manually/single { 200 401 403 404 }
- [ ] answer/local/manually/multiple { 200 401 403 404 }
- [ ] answer/local/automatic/single { 400 405 406 409 501 502 503 504 505 }
- [ ] answer/local/automatic/multiple { 400 405 406 409 501 502 503 504 505 }

more
- [ ] answer/local/subscription/bind/method { get post put patch delete } ?
- [ ] answer/tcp/single-step/ok { get post put patch delete }
- [ ] answer/tcp/single-step/subscription ?
- [ ] answer/bad-dispatch { malformed-endpoint method-missing resource-missing endpoint-missing }
- [ ] answer/not-acceptable
- [ ] answer/method-not-allowed
- [ ] answer/timeout
- [ ] answer/unrecognized-transport-protocol
- [ ] answer/missing-callback

**special cases**
- [ ] double bind: two emitters bound to \* User?
